### ISSUE TITLE
Potential HF demo?

### ISSUE THREAD

**Issue by xianbaoqian** [CodingLucasLi/GPT_Resume_analysing#1]
This project looks pretty cool. Would you like to consider creating a demo on HF? HF Spaces provide free instance with 16GB ram and 2vCPU.

Here is a tutorial on how to use HF with Streamlit: https://huggingface.co/docs/hub/spaces-sdks-streamlit

WDYT? Happy to help if you run into any issues :-)

**Comment by CodingLucasLi** [comment]
sorry, i dont have time to dao that in huggingface, please feel free to git and share your codes~

**Comment by CodingLucasLi** [comment]
this is not an issue, please do not use issue as a comment lol~
